// Generated by Avo VERSION 56.1.0, PLEASE EDIT WITH CARE
package app.avo.androidanalyticsdebugger;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.net.URL;
import java.util.Date;
import java.util.Locale;
import java.util.TimeZone;
import java.text.SimpleDateFormat;
import javax.net.ssl.HttpsURLConnection;

import android.os.AsyncTask;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.json.JSONException;
import org.json.JSONArray;
import org.json.JSONObject;

import android.util.Log;

public final class DebuggerAnalytics {
    public enum AvoEnv {
        PROD,
        DEV;
    }

    private static boolean __STRICT__ = true;
    private static AvoEnv __AVO_ENV__ = null;

    private static Object __MOBILE_DEBUGGER__ = null;

    private static boolean __MOBILE_DEBUGGER_ENABLED__() {
        if (__MOBILE_DEBUGGER__ != null) {
            try {
                Method method = __MOBILE_DEBUGGER__.getClass().getMethod("isEnabled");
                return Boolean.TRUE.equals(method.invoke(__MOBILE_DEBUGGER__));
            } catch (NoSuchMethodException e) {
                e.printStackTrace();
                return false;
            } catch (IllegalAccessException e) {
                e.printStackTrace();
                return false;
            } catch (InvocationTargetException e) {
                e.printStackTrace();
                return false;
            }
        } else {
            return false;
        }
    }

    private static void __MOBILE_DEBUGGER_POST_EVENT__(String id, long timestamp, String name, List<Map<String, String>> messages, List<Map<String, String>> eventProperties, List<Map<String, String>> userProperties) {
        if (__MOBILE_DEBUGGER__ != null) {
            try {
                Method method = __MOBILE_DEBUGGER__.getClass().getMethod("publishEvent",
                    String.class, Long.class, String.class, List.class, List.class,
                    List.class);
                method.invoke(__MOBILE_DEBUGGER__,
                    id, timestamp, name, messages, eventProperties, userProperties);
            } catch (NoSuchMethodException e) {
                e.printStackTrace();
            } catch (IllegalAccessException e) {
                e.printStackTrace();
            } catch (InvocationTargetException e) {
                e.printStackTrace();
            }
        }
    }

    private interface ISerializable {
        Map<String, Object> serialize();
    }

    private static <T> List<String> strings(List<T> objects) {
        final List<String> list = new ArrayList<>();
        for (T t: objects) {
            if (t != null) {
                list.add(t.toString());
            }
        }
        return list;
    }

    private static <T extends ISerializable> List<Map<String, Object>> objects(List<T> objects) {
        final List<Map<String, Object>> list = new ArrayList<>();
        for (T t: objects) {
            if (t != null) {
                list.add(t.serialize());
            }
        }
        return list;
    }

    private interface AvoAssertMessage {
        String getPropertyId();

        String getAssertionType();

        String getMessage();
    }

    private static class AvoAssertMax implements AvoAssertMessage {
        private final String propertyId;
        private final String message;

        AvoAssertMax(String propertyId, String message) {
            this.propertyId = propertyId;
            this.message = message;
        }

        public String getPropertyId() { return propertyId; }

        public String getAssertionType() { return "expectedMax"; }

        public String getMessage() { return message; }
    }

    private static class AvoAssertMin implements AvoAssertMessage {
        private final String propertyId;
        private final String message;

        AvoAssertMin(String propertyId, String message) {
            this.propertyId = propertyId;
            this.message = message;
        }

        public String getPropertyId() { return propertyId; }

        public String getAssertionType() { return "expectedMin"; }

        public String getMessage() { return message; }
    }

    private static class AvoAssertNonOptional implements AvoAssertMessage {
        private final String propertyId;
        private final String message;

        AvoAssertNonOptional(String propertyId, String message) {
            this.propertyId = propertyId;
            this.message = message;
        }

        public String getPropertyId() { return propertyId; }

        public String getAssertionType() { return "expectedNonOptional"; }

        public String getMessage() { return message; }
    }

    static class AvoAssert {
        static List<AvoAssertMessage> assertMax(String propertyId, String property, double max, double value) {
            if (value > max) {
                return Collections.<AvoAssertMessage>singletonList(new AvoAssertMax(propertyId, property + " has a maximum value of " + max + " but you provided the value " + value));
            }
            return Collections.emptyList();
        }

        static List<AvoAssertMessage> assertMax(String propertyId, String property, int max, int value) {
            if (value > max) {
                return Collections.<AvoAssertMessage>singletonList(new AvoAssertMax(propertyId, property + " has a maximum value of " + max + " but you provided the value " + value ));
            }
            return Collections.emptyList();
        }

        static List<AvoAssertMessage> assertMax(String propertyId, String property, long max, long value) {
            if (value > max) {
                return Collections.<AvoAssertMessage>singletonList(new AvoAssertMax(propertyId, property + " has a maximum value of " + max + " but you provided the value " + value));
            }
            return Collections.emptyList();
        }

        static List<AvoAssertMessage> assertMin(String propertyId, String property, double min, double value) {
            if (value < min) {
                return Collections.<AvoAssertMessage>singletonList(new AvoAssertMin(propertyId, property + " has a minimum value of " + min + " but you provided the value " + value));
            }
            return Collections.emptyList();
        }

        static List<AvoAssertMessage> assertMin(String propertyId, String property, int min, int value) {
            if (value < min) {
                return Collections.<AvoAssertMessage>singletonList(new AvoAssertMin(propertyId, property + " has a minimum value of " + min + " but you provided the value " + value));
            }
            return Collections.emptyList();
        }

        static List<AvoAssertMessage> assertMin(String propertyId, String property, long min, long value) {
            if (value < min) {
                return Collections.<AvoAssertMessage>singletonList(new AvoAssertMin(propertyId, property + " has a minimum value of " + min + " but you provided the value " + value));
            }
            return Collections.emptyList();
        }

        static <T> List<AvoAssertMessage> assertNonOptional(String propertyId, String property, T prop) {
            if (prop == null) {
                return Collections.<AvoAssertMessage>singletonList(new AvoAssertNonOptional(propertyId, property + " is a required property but you provided null"));
            }
            return Collections.emptyList();
        }
    }


    private static final String TAG = "Avo";

    static class AvoLogger {
        static void logEventSent(String eventName, Map<String, Object> eventProps, Map<String, Object> userProps) {
            Log.i(TAG, "[avo] Event Sent: " + eventName + " Event Props: " +
              (eventProps != null ? eventProps : "empty") + " User Props: " +
              (userProps != null ? userProps : "empty"));
        }
    }


    public static interface ICustomDestination {
        void make(AvoEnv env);

        void logEvent(String eventName, Map<String, Object> eventProperties);

        void setUserProperties(String userId, Map<String, Object> userProperties);

        void identify(String userId);

        void unidentify();
    }


private static class AvoInvoke {
    interface Callback {
        void apply(Double sa);
    }

    private static class HttpPostAsyncTask extends AsyncTask<String, Void, Void> {
        final JSONObject json;
        final Callback onComplete;
        HttpPostAsyncTask(JSONObject json, Callback onComplete) {
            this.json = json;
            this.onComplete = onComplete;
        }

        @Override
        protected Void doInBackground(String... strings) {
            try {
                HttpsURLConnection connection = (HttpsURLConnection) new URL("https://api.avo.app/i").openConnection();
                connection.setRequestMethod("POST");
                connection.setDoOutput(true);
                connection.setRequestProperty("Content-Type", "application/json");

                OutputStreamWriter writer = new OutputStreamWriter(connection.getOutputStream());
                writer.write(json.toString());
                writer.flush();

                int statusCode = connection.getResponseCode();
                if (statusCode == 200) {
                    BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
                    try {
                        StringBuffer response = new StringBuffer();
                        String inputLine = reader.readLine();
                        while (inputLine != null) {
                            response.append(inputLine);
                            inputLine = reader.readLine();
                        }
                        JSONObject json = new JSONObject(response.toString());
                        onComplete.apply(json.getDouble("sa"));
                    } finally {
                        reader.close();
                    }
                }
                connection.disconnect();
                return null;
            } catch (Throwable e) {
                return null;
            }
        }
    }

    static private double samplingRate = 1.0;

    static void _invoke(String eventId, String hash, List<AvoAssertMessage> messages) throws JSONException {
        if (samplingRate > 0) {
            if (Math.random() < samplingRate) {
                JSONObject json = new JSONObject();
                json.put("ac", "1mtjOvDJcYwj5vfTAU9B");
                json.put("br", "LowQacyet");
                json.put("en", "dev");
                json.put("ev", eventId);
                json.put("ha", hash);
                json.put("sc", "fwtXqAc0fCLy7b7oGW40");
                json.put("se", toISO8601UTC(new Date()));
                json.put("so", "-nnOlYqP6");
                json.put("va", messages.isEmpty());
                json.put("or", "event");

                JSONArray me = new JSONArray();
                for (AvoAssertMessage message: messages) {
                    JSONObject obj = new JSONObject();
                    obj.put("tag", message.getAssertionType());
                    obj.put("propertyId", message.getPropertyId());
                    me.put(obj);
                }
                json.put("me", me);

                new HttpPostAsyncTask(json, new Callback() {
                    @Override
                    public void apply(Double rate) {
                        samplingRate = rate;
                    }
                }).execute();
            }
        }
    }

    static void invoke(String eventId, String hash, List<AvoAssertMessage> messages) {
        try {
            _invoke(eventId, hash, messages);
        } catch (JSONException e) {
            throw new RuntimeException(e);
        }
    }

    static void _invokeMeta(String type, List<AvoAssertMessage> messages) throws JSONException {
        if (samplingRate > 0) {
            if (Math.random() < samplingRate) {
                JSONObject json = new JSONObject();
                json.put("ac", "1mtjOvDJcYwj5vfTAU9B");
                json.put("br", "LowQacyet");
                json.put("en", "dev");
                json.put("ty", type);
                json.put("sc", "fwtXqAc0fCLy7b7oGW40");
                json.put("se", toISO8601UTC(new Date()));
                json.put("so", "-nnOlYqP6");
                json.put("va", messages.isEmpty());

                JSONArray me = new JSONArray();
                for (AvoAssertMessage message: messages) {
                    JSONObject obj = new JSONObject();
                    obj.put("tag", message.getAssertionType());
                    obj.put("propertyId", message.getPropertyId());
                    me.put(obj);
                }
                json.put("me", me);

                new HttpPostAsyncTask(json, new Callback() {
                    @Override
                    public void apply(Double rate) {
                        samplingRate = rate;
                    }
                }).execute();
            }
        }
    }

    static void invokeMeta(String type, List<AvoAssertMessage> messages) {
        try {
            _invokeMeta(type, messages);
        } catch (JSONException e) {
            throw new RuntimeException(e);
        }
    }

    static String toISO8601UTC(Date date) {
        TimeZone tz = TimeZone.getTimeZone("UTC");
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm'Z'", Locale.US);
        df.setTimeZone(tz);
        return df.format(date);
    }
}

    public enum Client {
        CLOUD_FUNCTIONS("Cloud Functions"),
        WEB("Web"),
        LANDING_PAGE("Landing Page"),
        CLI("Cli"),
        WEB_DEBUGGER("Web Debugger"),
        ANDROID_DEBUGGER("Android Debugger"),
        IOS_DEBUGGER("Ios Debugger"),
        REACT_NATIVE_DEBUGGER_IOS("React Native Debugger (ios)"),
        REACT_NATIVE_DEBUGGER_ANDROID("React Native Debugger (android)");

        private String value;

        Client(final String value) {
            this.value = value;
        }

        @Override
        public String toString() {
            return value;
        }
    }

    private static Client CLIENT = null;
    private static String VERSION = null;

    public static void setSystemProperties(Client client, String version) {
        if (client != null) {
            CLIENT = client;
            assertClient(CLIENT);
        }
        if (version != null) {
            VERSION = version;
            assertVersion(VERSION);
        }
    }

    private static ICustomDestination customNodeJs = null;

    public static void initAvo(AvoEnv env, Client client, String version,
                               ICustomDestination customNodeJsDestination) {
        initAvo(env, client, version, customNodeJsDestination, true);
    }

    public static void initAvo(AvoEnv env, Client client, String version,
                               ICustomDestination customNodeJsDestination,
                               Object debuggerManager) {
        __MOBILE_DEBUGGER__ = debuggerManager;
        initAvo(env, client, version, customNodeJsDestination, false);
    }

    public static void initAvo(AvoEnv env, Client client, String version,
                               ICustomDestination customNodeJsDestination,
                               boolean strict, Object debuggerManager) {
        __MOBILE_DEBUGGER__ = debuggerManager;
        initAvo(env, client, version, customNodeJsDestination, strict);
    }

    public static void initAvo(AvoEnv env, Client client, String version,
                               ICustomDestination customNodeJsDestination,
                               boolean strict) {
        __STRICT__ = strict;
        __AVO_ENV__ = env;

        setSystemProperties(client, version);

        if (__AVO_ENV__ == AvoEnv.PROD) {
        }
        if (__AVO_ENV__ == AvoEnv.DEV) {
        }
        customNodeJs = customNodeJsDestination;
        customNodeJs.make(env);
        if (__AVO_ENV__ != AvoEnv.PROD) {
            // debug console in Avo
            AvoInvoke.invokeMeta("init", Collections.<AvoAssertMessage>emptyList());
        }
    }

    private static List<AvoAssertMessage> assertVersion(String version) {
        final List<AvoAssertMessage> messages = new ArrayList<>();
        messages.addAll(AvoAssert.assertNonOptional("2fad5bf3-7782-49a2-acc2-825daf823095", "Version", version));
        return messages;
    }

    private static List<AvoAssertMessage> assertSchemaId(String schemaId) {
        final List<AvoAssertMessage> messages = new ArrayList<>();
        messages.addAll(AvoAssert.assertNonOptional("40958e87-d69a-4d5a-98f8-b36922466787", "Schema Id", schemaId));
        return messages;
    }

    private static List<AvoAssertMessage> assertClient(Client client) {
        final List<AvoAssertMessage> messages = new ArrayList<>();
        messages.addAll(AvoAssert.assertNonOptional("9e5c4ff5-d5f6-4e82-b061-d5fa02755aae", "Client", client));
        return messages;
    }

    /**
     * Debugger Started: Sent when the web debugger is started.
     *
     * @param frameLocation Describes from where the debugger was started.
     * @param schemaId The ID of the schema that this event is related to.
     *
     * @see <a href="https://www.avo.app/schemas/fwtXqAc0fCLy7b7oGW40/branches/LowQacyet/events/Od3PNKHK1">Debugger Started</a>
     */
    public static void debuggerStarted(final String frameLocation,
                                       final String schemaId) {
        // assert properties
        if (__AVO_ENV__ != AvoEnv.PROD || __MOBILE_DEBUGGER_ENABLED__()) {
            final List<AvoAssertMessage> messages = new ArrayList<>();
            messages.addAll(assertSchemaId(schemaId));
            messages.addAll(assertClient(CLIENT));
            messages.addAll(assertVersion(VERSION));
            // debug console in Avo
            AvoInvoke.invoke("Od3PNKHK1", "ddeac45c0b1b8ad9c292aec978dc7b0a20d3de36ef5e8a042d75b7ce2c07117d", messages);
            if ((__AVO_ENV__ != AvoEnv.PROD && __MOBILE_DEBUGGER__ != null) || (__AVO_ENV__ == AvoEnv.PROD && __MOBILE_DEBUGGER_ENABLED__())) {
                // Avo mobile debugger
                __MOBILE_DEBUGGER_POST_EVENT__("Od3PNKHK1", System.currentTimeMillis(), "Debugger Started", new ArrayList<Map<String, String>>() {{
                    for (final AvoAssertMessage message: messages) {
                        add(new HashMap<String, String>() {{
                            put("tag", message.getAssertionType());
                            put("propertyId", message.getPropertyId());
                            put("message", message.getMessage());
                        }});
                    }
                }}, new ArrayList<Map<String, String>>() {{
                    add(new HashMap<String, String>() {{
                        put("id", "zXjbg4Ek9");
                        put("name", "Frame Location");
                        put("value", frameLocation != null ? frameLocation.toString() : "");
                    }});
                    add(new HashMap<String, String>() {{
                        put("id", "40958e87-d69a-4d5a-98f8-b36922466787");
                        put("name", "Schema Id");
                        put("value", schemaId != null ? schemaId.toString() : "");
                    }});
                    add(new HashMap<String, String>() {{
                        put("id", "9e5c4ff5-d5f6-4e82-b061-d5fa02755aae");
                        put("name", "Client");
                        put("value", CLIENT != null ? CLIENT.toString().toString() : "");
                    }});
                    add(new HashMap<String, String>() {{
                        put("id", "2fad5bf3-7782-49a2-acc2-825daf823095");
                        put("name", "Version");
                        put("value", VERSION != null ? VERSION.toString() : "");
                    }});
                }}, new ArrayList<Map<String, String>>() {{
                }});
            }
            if (__AVO_ENV__ != AvoEnv.PROD && __STRICT__) {
                // throw exception if messages is not empty
                if (!messages.isEmpty()) {
                    throw new IllegalArgumentException("Error sending event 'Debugger Started': " + messages.get(0).getMessage());
                }
            } else {
                for (AvoAssertMessage m: messages) {
                    Log.w(TAG, "[avo] " + m.getMessage());
                }
            }
        }

        if (__AVO_ENV__ != AvoEnv.PROD) {
            final Map<String, Object> avoLogEventProperties = new HashMap<>();
            if (frameLocation != null) {
                avoLogEventProperties.put("Frame Location", frameLocation);
            }
            if (schemaId != null) {
                avoLogEventProperties.put("Schema Id", schemaId);
            }
            if (CLIENT != null) {
                avoLogEventProperties.put("Client", CLIENT.toString());
            }
            if (VERSION != null) {
                avoLogEventProperties.put("Version", VERSION);
            }

            final Map<String, Object> avoLogUserProperties = new HashMap<>();

            AvoLogger.logEventSent("Debugger Started", avoLogEventProperties, avoLogUserProperties);
        }

        // destination customNodeJs
        final Map<String, Object> customNodeJsEventProperties = new HashMap<>();
        if (frameLocation != null) {
            customNodeJsEventProperties.put("Frame Location", frameLocation);
        }
        if (schemaId != null) {
            customNodeJsEventProperties.put("Schema Id", schemaId);
        }
        if (CLIENT != null) {
            customNodeJsEventProperties.put("Client", CLIENT.toString());
        }
        if (VERSION != null) {
            customNodeJsEventProperties.put("Version", VERSION);
        }

        final Map<String, Object> customNodeJsUserProperties = new HashMap<>();

        customNodeJs.logEvent("Debugger Started", customNodeJsEventProperties);
    }


}
// AVOMODULEMAP:"DebuggerAnalytics"
// AVOEVENTMAP:["debuggerStarted"]
